using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Bizigo.ControlPlane.Migrations;

[DbContext(typeof(ControlPlaneDbContext))]
[Migration("20260926160000_AddTelemetryOwnership")]
public sealed class AddTelemetryOwnership : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE bizigo.source_ownership_history (
                revision bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_source_ownership_history PRIMARY KEY,
                source_id varchar(128) NOT NULL,
                owner_group varchar(64) NOT NULL,
                peer_address varchar(256),
                hostname varchar(256),
                enabled boolean NOT NULL,
                effective_from_nano numeric(20,0) NOT NULL,
                effective_to_nano numeric(20,0),
                CONSTRAINT ck_source_history_interval CHECK
                    (effective_from_nano >= 0 AND (effective_to_nano IS NULL OR effective_to_nano > effective_from_nano))
            );
            CREATE UNIQUE INDEX ix_source_ownership_history_source_id_effective_from_nano
                ON bizigo.source_ownership_history (source_id,effective_from_nano);
            CREATE UNIQUE INDEX ix_source_ownership_history_source_id
                ON bizigo.source_ownership_history (source_id) WHERE effective_to_nano IS NULL;
            CREATE TABLE bizigo.telemetry_owner_claims (
                envelope_id uuid CONSTRAINT pk_telemetry_owner_claims PRIMARY KEY,
                binding_hash varchar(64) NOT NULL
            );
            -- An existing current row proves ownership only from this migration
            -- onward. CreatedAt cannot establish who owned older telemetry.
            INSERT INTO bizigo.source_ownership_history
                (source_id,owner_group,peer_address,hostname,enabled,effective_from_nano)
            SELECT source_id,owner_group,peer_address,hostname,enabled,
                (extract(epoch FROM transaction_timestamp()) * 1000000000)::numeric(20,0)
            FROM bizigo.sources;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // Historical bindings are a required restore dependency. An explicit
        // destructive downgrade must be performed from an operator backup.
        throw new NotSupportedException("Telemetry ownership history cannot be dropped by an automatic downgrade.");
    }
}
