// <auto-generated />
using System;
using Bizigo.ControlPlane;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bizigo.ControlPlane.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    [Migration("20260820102421_AddConfigSnapshots")]
    partial class AddConfigSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bizigo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bizigo.ControlPlane.AlertRuleChannelEntity", b =>
                {
                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.HasKey("RuleId", "ChannelId")
                        .HasName("pk_alert_rule_channels");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_alert_rule_channels_channel_id");

                    b.ToTable("alert_rule_channels", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.AlertRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Comparison")
                        .HasColumnType("integer")
                        .HasColumnName("comparison");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_seconds");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastFiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fired_at");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<int>("LastRunState")
                        .HasColumnType("integer")
                        .HasColumnName("last_run_state");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<string>("OwnerGroups")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("owner_groups");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_subject");

                    b.Property<int>("RepeatIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_interval_seconds");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer")
                        .HasColumnName("rule_type");

                    b.Property<string>("SearchJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_json");

                    b.Property<int>("SilenceSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("silence_seconds");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("window_seconds");

                    b.HasKey("Id")
                        .HasName("pk_alert_rules");

                    b.HasIndex("Enabled", "NextRunAt")
                        .HasDatabaseName("ix_alert_rules_enabled_next_run_at");

                    b.ToTable("alert_rules", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.AlertTriggerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fired_at");

                    b.Property<string>("OwnerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_group");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("summary");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.Property<DateTimeOffset>("WindowFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_from");

                    b.Property<DateTimeOffset>("WindowTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_to");

                    b.HasKey("Id")
                        .HasName("pk_alert_triggers");

                    b.HasIndex("FiredAt")
                        .HasDatabaseName("ix_alert_triggers_fired_at");

                    b.HasIndex("RuleId", "FiredAt")
                        .HasDatabaseName("ix_alert_triggers_rule_id_fired_at");

                    b.ToTable("alert_triggers", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("details");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource");

                    b.Property<long>("RowCount")
                        .HasColumnType("bigint")
                        .HasColumnName("row_count");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("scope");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_audit_log_at");

                    b.HasIndex("Subject", "At")
                        .HasDatabaseName("ix_audit_log_subject_at");

                    b.ToTable("audit_log", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.ChangeConfigSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Guid>("ConnectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_id");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer")
                        .HasColumnName("line_count");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.HasKey("Id")
                        .HasName("pk_change_config_snapshots");

                    b.HasIndex("ConnectorId", "CapturedAt")
                        .HasDatabaseName("ix_change_config_snapshots_connector_id_captured_at");

                    b.ToTable("change_config_snapshots", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.ChangeConnectorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_json");

                    b.Property<byte>("ConnectorType")
                        .HasColumnType("smallint")
                        .HasColumnName("connector_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialCipher")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("credential_cipher");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int?>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_seconds");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<byte?>("LastRunState")
                        .HasColumnType("smallint")
                        .HasColumnName("last_run_state");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<string>("OwnerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_group");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_change_connectors");

                    b.HasIndex("OwnerGroup")
                        .HasDatabaseName("ix_change_connectors_owner_group");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_change_connectors_slug");

                    b.HasIndex("Enabled", "NextRunAt")
                        .HasDatabaseName("ix_change_connectors_enabled_next_run_at");

                    b.ToTable("change_connectors", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.ChangeConnectorRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ChangesWritten")
                        .HasColumnType("integer")
                        .HasColumnName("changes_written");

                    b.Property<Guid>("ConnectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_id");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<byte>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_change_connector_runs");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_change_connector_runs_started_at");

                    b.HasIndex("ConnectorId", "StartedAt")
                        .HasDatabaseName("ix_change_connector_runs_connector_id_started_at");

                    b.ToTable("change_connector_runs", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.ChangeWebhookDeliveryEntity", b =>
                {
                    b.Property<string>("DeliveryKey")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("delivery_key");

                    b.Property<Guid>("ChangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("change_id");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("OwnerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_group");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("DeliveryKey")
                        .HasName("pk_change_webhook_deliveries");

                    b.HasIndex("EndpointId", "ReceivedAt")
                        .HasDatabaseName("ix_change_webhook_deliveries_endpoint_id_received_at");

                    b.ToTable("change_webhook_deliveries", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.IdpGroupMappingEntity", b =>
                {
                    b.Property<string>("IdpGroup")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idp_group");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("note");

                    b.Property<string>("OwnerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_group");

                    b.HasKey("IdpGroup")
                        .HasName("pk_idp_group_mapping");

                    b.ToTable("idp_group_mapping", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.MaintenanceWindowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("OwnerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_group");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id")
                        .HasName("pk_alert_maintenance_windows");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_alert_maintenance_windows_rule_id");

                    b.HasIndex("OwnerGroup", "StartsAt", "EndsAt")
                        .HasDatabaseName("ix_alert_maintenance_windows_owner_group_starts_at_ends_at");

                    b.ToTable("alert_maintenance_windows", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.NotificationChannelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChannelType")
                        .HasColumnType("integer")
                        .HasColumnName("channel_type");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_group");

                    b.Property<string>("SecretCipher")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret_cipher");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notification_channels");

                    b.HasIndex("OwnerGroup")
                        .HasDatabaseName("ix_notification_channels_owner_group");

                    b.HasIndex("Name", "OwnerGroup")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_channels_name_owner_group");

                    b.ToTable("notification_channels", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.NotificationDeliveryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<Guid>("TriggerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trigger_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_deliveries");

                    b.HasIndex("TriggerId")
                        .HasDatabaseName("ix_notification_deliveries_trigger_id");

                    b.HasIndex("State", "NextAttemptAt")
                        .HasDatabaseName("ix_notification_deliveries_state_next_attempt_at");

                    b.ToTable("notification_deliveries", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.ParserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner");

                    b.Property<string>("ParserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("parser_id");

                    b.Property<int>("PassingTests")
                        .HasColumnType("integer")
                        .HasColumnName("passing_tests");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("QuarantineReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("quarantine_reason");

                    b.Property<bool>("Quarantined")
                        .HasColumnType("boolean")
                        .HasColumnName("quarantined");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vendor");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.Property<string>("Yaml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yaml");

                    b.HasKey("Id")
                        .HasName("pk_parsers");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_parsers_state");

                    b.HasIndex("ParserId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_parsers_parser_id_version");

                    b.ToTable("parsers", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.RawManifestEntity", b =>
                {
                    b.Property<string>("ObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer")
                        .HasColumnName("event_count");

                    b.Property<DateTimeOffset?>("LastScrubbedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scrubbed_at");

                    b.Property<string>("OwnerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_group");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("TsFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_from");

                    b.Property<DateTimeOffset>("TsTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_to");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<string>("WalSegment")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("wal_segment");

                    b.HasKey("ObjectKey")
                        .HasName("pk_raw_manifest");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_raw_manifest_state");

                    b.HasIndex("VerifiedAt")
                        .HasDatabaseName("ix_raw_manifest_verified_at");

                    b.HasIndex("WalSegment")
                        .HasDatabaseName("ix_raw_manifest_wal_segment");

                    b.HasIndex("OwnerGroup", "TsFrom")
                        .HasDatabaseName("ix_raw_manifest_owner_group_ts_from");

                    b.ToTable("raw_manifest", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.SourceEntity", b =>
                {
                    b.Property<string>("SourceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Encoding")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("encoding");

                    b.Property<string>("Hostname")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hostname");

                    b.Property<string>("OwnerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_group");

                    b.Property<string>("ParserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("parser_id");

                    b.Property<string>("PeerAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("peer_address");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product");

                    b.Property<string>("SourceClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_class");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vendor");

                    b.HasKey("SourceId")
                        .HasName("pk_sources");

                    b.HasIndex("Hostname")
                        .HasDatabaseName("ix_sources_hostname");

                    b.HasIndex("OwnerGroup")
                        .HasDatabaseName("ix_sources_owner_group");

                    b.HasIndex("PeerAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_peer_address")
                        .HasFilter("peer_address IS NOT NULL");

                    b.ToTable("sources", "bizigo");
                });
#pragma warning restore 612, 618
        }
    }
}
