// <auto-generated />
using System;
using Bizigo.ControlPlane;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bizigo.ControlPlane.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    partial class ControlPlaneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bizigo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bizigo.ControlPlane.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("details");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource");

                    b.Property<long>("RowCount")
                        .HasColumnType("bigint")
                        .HasColumnName("row_count");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("scope");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_audit_log_at");

                    b.HasIndex("Subject", "At")
                        .HasDatabaseName("ix_audit_log_subject_at");

                    b.ToTable("audit_log", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.IdpGroupMappingEntity", b =>
                {
                    b.Property<string>("IdpGroup")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idp_group");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("note");

                    b.Property<string>("OwnerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_group");

                    b.HasKey("IdpGroup")
                        .HasName("pk_idp_group_mapping");

                    b.ToTable("idp_group_mapping", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.ParserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner");

                    b.Property<string>("ParserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("parser_id");

                    b.Property<int>("PassingTests")
                        .HasColumnType("integer")
                        .HasColumnName("passing_tests");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("QuarantineReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("quarantine_reason");

                    b.Property<bool>("Quarantined")
                        .HasColumnType("boolean")
                        .HasColumnName("quarantined");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vendor");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.Property<string>("Yaml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yaml");

                    b.HasKey("Id")
                        .HasName("pk_parsers");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_parsers_state");

                    b.HasIndex("ParserId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_parsers_parser_id_version");

                    b.ToTable("parsers", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.RawManifestEntity", b =>
                {
                    b.Property<string>("ObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer")
                        .HasColumnName("event_count");

                    b.Property<DateTimeOffset?>("LastScrubbedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scrubbed_at");

                    b.Property<string>("OwnerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_group");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("TsFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_from");

                    b.Property<DateTimeOffset>("TsTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_to");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("ObjectKey")
                        .HasName("pk_raw_manifest");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_raw_manifest_state");

                    b.HasIndex("VerifiedAt")
                        .HasDatabaseName("ix_raw_manifest_verified_at");

                    b.HasIndex("OwnerGroup", "TsFrom")
                        .HasDatabaseName("ix_raw_manifest_owner_group_ts_from");

                    b.ToTable("raw_manifest", "bizigo");
                });

            modelBuilder.Entity("Bizigo.ControlPlane.SourceEntity", b =>
                {
                    b.Property<string>("SourceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Encoding")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("encoding");

                    b.Property<string>("Hostname")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hostname");

                    b.Property<string>("OwnerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_group");

                    b.Property<string>("ParserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("parser_id");

                    b.Property<string>("PeerAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("peer_address");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product");

                    b.Property<string>("SourceClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_class");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vendor");

                    b.HasKey("SourceId")
                        .HasName("pk_sources");

                    b.HasIndex("Hostname")
                        .HasDatabaseName("ix_sources_hostname");

                    b.HasIndex("OwnerGroup")
                        .HasDatabaseName("ix_sources_owner_group");

                    b.HasIndex("PeerAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_peer_address")
                        .HasFilter("peer_address IS NOT NULL");

                    b.ToTable("sources", "bizigo");
                });
#pragma warning restore 612, 618
        }
    }
}
