namespace Bizigo.IntegrationTests;

internal static class IntegrationTestEntryPoint
{
    public static async Task<int> Main(string[] args)
    {
        if (args.Length == 2 && args[0] == "--s04-golden-restart")
            return await GoldenReviewRestartProbe.RunAsync(args[1]);
        return AutoGenerated.XunitAutoGeneratedEntryPoint.Main(args);
    }
}
