<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Bizigo.Query\Bizigo.Query.csproj" />
    <ProjectReference Include="..\Bizigo.Ingest\Bizigo.Ingest.csproj" />
    <ProjectReference Include="..\Bizigo.Replay\Bizigo.Replay.csproj" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

</Project>
