#config-version=FGT100E-7.4.4-FW-build2662-240613:opmode=0:vdom=0
#conf_file_ver=8
#buildno=2662
#global_vdom=1
config system global
    set hostname "fw-izmir-01"
    set timezone 34
end
config system interface
    edit "port12"
        set ip 10.9.9.1 255.255.255.0
    next
    edit "port1"
        set allowaccess ping https ssh
        set ip 10.1.1.1 255.255.255.0
    next
end
config vpn ipsec phase1-interface
    edit "vpn-merkez"
        set interface "port1"
        set psksecret ENC pW4sD9fG2hJ5kL8n
        set proposal aes256-sha256
    next
end
config firewall policy
    edit 1
        set name "izin-ic-disari"
        set srcintf "port12"
        set dstintf "port1"
        set action accept
        set service "HTTPS"
    next
end
