/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OtlpLogs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/changes/webhooks/{endpointId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReceiveChangeWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PipelineHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Replay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parsers/{parserId}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RollbackParser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parsers/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ParserCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ingest/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/discovery/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SearchEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetEventRaw"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListSources"];
        put?: never;
        post: operations["UpsertSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ImportSourcesCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SearchChanges"];
        put?: never;
        post: operations["WriteChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/changes/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListChangeConnectors"];
        put?: never;
        post: operations["CreateChangeConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/changes/connectors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetChangeConnector"];
        put: operations["UpdateChangeConnector"];
        post?: never;
        delete: operations["DeleteChangeConnector"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/changes/connectors/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TestChangeConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/changes/connectors/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListChangeConnectorRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parsers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListParsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parsers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetParser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parsers/try": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TryParser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parsers/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListParserDrafts"];
        put?: never;
        post: operations["CreateParserDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parsers/drafts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetParserDraft"];
        put: operations["UpdateParserDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parsers/drafts/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SubmitParserDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parsers/drafts/{id}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReturnParserDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parsers/drafts/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PublishParserDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAlertRules"];
        put?: never;
        post: operations["CreateAlertRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAlertRule"];
        put: operations["UpdateAlertRule"];
        post?: never;
        delete: operations["DeleteAlertRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/rules/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PreviewAlertRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAlertTriggers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListMaintenanceWindows"];
        put?: never;
        post: operations["CreateMaintenanceWindow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/maintenance/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["DeleteMaintenanceWindow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlertingStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListNotificationChannels"];
        put?: never;
        post: operations["CreateNotificationChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdateNotificationChannel"];
        post?: never;
        delete: operations["DeleteNotificationChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/channels/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TestNotificationChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlertDeliveryResponse: {
            /** Format: uuid */
            channel_id: string;
            channel_name: string;
            channel_type: null | string;
            state: string;
            /** Format: int32 */
            attempts: number | string;
            /** Format: date-time */
            delivered_at: null | string;
            /** Format: date-time */
            next_attempt_at: null | string;
            last_error: string;
        };
        AlertingNotificationStats: {
            /** Format: int64 */
            queued: number | string;
            /** Format: int64 */
            delivered: number | string;
            /** Format: int64 */
            retried: number | string;
            /** Format: int64 */
            abandoned: number | string;
        };
        AlertingStatsResponse: {
            /** Format: int64 */
            turns: number | string;
            /** Format: int64 */
            evaluated: number | string;
            /** Format: int64 */
            fired: number | string;
            /** Format: int64 */
            suppressed: number | string;
            /** Format: int64 */
            timed_out: number | string;
            /** Format: int64 */
            failed: number | string;
            /** Format: int64 */
            scoped_queries: number | string;
            notifications: components["schemas"]["AlertingNotificationStats"];
        };
        AlertPreviewResponse: {
            rule_type: string;
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /** Format: int32 */
            bucket_seconds: number | string;
            /** Format: double */
            threshold: number | string;
            /** Format: int32 */
            firing_count: number | string;
            note: string;
            points: components["schemas"]["PreviewPointResponse"][];
            sources: components["schemas"]["PreviewSourceResponse"][];
        };
        AlertRuleDetailResponse: {
            rule: components["schemas"]["AlertRuleResponse"];
            channel_ids: string[];
        };
        AlertRuleListResponse: {
            /** Format: int32 */
            count: number | string;
            rules: components["schemas"]["AlertRuleResponse"][];
        };
        AlertRuleRequest: {
            name: string;
            description?: string;
            ruleType?: string;
            ownerGroups?: string[];
            fullText?: null | string;
            filters?: components["schemas"]["FieldFilterRequest"][];
            sourceIds?: string[];
            /** Format: int32 */
            windowSeconds?: number | string;
            /** Format: int32 */
            intervalSeconds?: number | string;
            /** Format: double */
            threshold?: number | string;
            comparison?: string;
            /** Format: int32 */
            silenceSeconds?: number | string;
            /** Format: int32 */
            repeatIntervalSeconds?: number | string;
            enabled?: boolean;
            channelIds?: string[];
        };
        AlertRuleResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            rule_type: string;
            owner_groups: string[];
            /** Format: int32 */
            window_seconds: number | string;
            /** Format: int32 */
            interval_seconds: number | string;
            /** Format: double */
            threshold: number | string;
            comparison: string;
            /** Format: int32 */
            silence_seconds: number | string;
            /** Format: int32 */
            repeat_interval_seconds: number | string;
            enabled: boolean;
            /** Format: date-time */
            next_run_at: null | string;
            /** Format: date-time */
            last_run_at: null | string;
            /** Format: date-time */
            last_fired_at: null | string;
            last_run_state: string;
            last_error: string;
            search: components["schemas"]["AlertSearchResponse"];
        };
        AlertSearchResponse: {
            full_text: null | string;
            filters: components["schemas"]["FieldFilterResponse"][];
            source_ids: string[];
        };
        AlertTriggerListResponse: {
            /** Format: int32 */
            count: number | string;
            triggers: components["schemas"]["AlertTriggerResponse"][];
        };
        AlertTriggerResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            rule_id: string;
            rule_name: string;
            /** Format: date-time */
            fired_at: string;
            /** Format: date-time */
            window_from: string;
            /** Format: date-time */
            window_to: string;
            /** Format: double */
            value: number | string;
            /** Format: double */
            threshold: number | string;
            source_id: string;
            owner_group: string;
            summary: string;
            deliveries: components["schemas"]["AlertDeliveryResponse"][];
        };
        AuthMeResponse: {
            subject: string;
            username: string;
            roles: string[];
            idp_groups: string[];
            owner_groups: string[];
            unrestricted: boolean;
            sees_nothing: boolean;
        };
        CatalogCoverageResponse: {
            /** Format: int32 */
            ok: number | string;
            /** Format: int32 */
            partial: number | string;
            /** Format: int32 */
            failed: number | string;
            /** Format: int32 */
            total: number | string;
            /** Format: date-time */
            measured_at: string;
            stale: boolean;
            by_parser: components["schemas"]["ParserCoverageEntryResponse"][];
        };
        CatalogReloadResponse: {
            /** Format: int32 */
            loaded: number | string;
            /** Format: int32 */
            from_repository: number | string;
            /** Format: int32 */
            from_database: number | string;
            shadowed: string[];
            errors: string[];
        };
        ChangeResponse: {
            /** Format: uuid */
            change_id: string;
            /** Format: date-time */
            timestamp: string;
            owner_group: string;
            target_kind: string;
            target_id: string;
            change_kind: string;
            actor: string;
            summary: string;
            details: {
                [key: string]: string;
            };
            source: string;
            external_ref: string;
        };
        ChangeSearchResponse: {
            /** Format: int32 */
            count: number | string;
            changes: components["schemas"]["ChangeResponse"][];
        };
        ChangeWriteRequest: {
            owner_group: string;
            target_kind: string;
            target_id: string;
            change_kind: string;
            /** Format: date-time */
            timestamp?: null | string;
            actor?: string;
            summary?: string;
            details?: {
                [key: string]: string;
            };
            source?: string;
            external_ref?: string;
        };
        ChangeWriteResponse: {
            /** Format: uuid */
            change_id: string;
        };
        ChannelSettingsResponse: {
            headers: {
                [key: string]: string;
            };
            host: string;
            /** Format: int32 */
            port: number | string;
            from: string;
            to: string[];
            user: string;
            use_start_tls: boolean;
        };
        ChannelTestResponse: {
            ok: boolean;
            error: string;
        };
        ConnectorListResponse: {
            /** Format: int32 */
            count: number | string;
            connectors: components["schemas"]["ConnectorView"][];
        };
        ConnectorRequest: {
            slug?: string;
            name?: string;
            connector_type?: string;
            owner_group?: string;
            config?: null | components["schemas"]["JsonElement"];
            credential?: null | string;
            /** Format: int32 */
            interval_seconds?: null | number | string;
            enabled?: boolean;
        };
        ConnectorRunListResponse: {
            /** Format: int32 */
            count: number | string;
            runs: components["schemas"]["ConnectorRunView"][];
        };
        ConnectorRunView: {
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at: string;
            state: string;
            /** Format: int32 */
            changes_written: number | string;
            error: string;
        };
        ConnectorTestResponse: {
            ok: boolean;
            message: string;
        };
        ConnectorView: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            connector_type: string;
            owner_group: string;
            config: components["schemas"]["JsonElement"];
            credential_set: boolean;
            credential: string;
            /** Format: int32 */
            interval_seconds: null | number | string;
            enabled: boolean;
            /** Format: date-time */
            next_run_at: null | string;
            /** Format: date-time */
            last_run_at: null | string;
            last_run_state: null | string;
            last_error: string;
            receive_path: null | string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreatedIdResponse: {
            /** Format: uuid */
            id: string;
        };
        ErrorResponse: {
            error: string;
        };
        EventCursorResponse: {
            /** Format: date-time */
            after_timestamp: string;
            /** Format: uuid */
            after_event_id: string;
        };
        EventDetailResponse: {
            event: components["schemas"]["EventResponse"];
            ocsf: components["schemas"]["EventFieldResponse"][];
            otel: components["schemas"]["EventFieldResponse"][];
        };
        EventFieldResponse: {
            name: string;
            value: string;
        };
        EventRawResponse: {
            /** Format: uuid */
            event_id: string;
            object_key: string;
            /** Format: int32 */
            objects_scanned: number | string;
            /** Format: date-time */
            received_at: string;
            source_key: string;
            transport: components["schemas"]["EventRawTransport"];
            encoding_declared: string;
            encoding_detected: string;
            raw_b64: string;
        };
        EventRawTransport: {
            proto: string;
            peer: string;
        };
        EventResponse: {
            /** Format: uuid */
            event_id: string;
            /** Format: date-time */
            ts: string;
            time_source: string;
            /** Format: date-time */
            ingested_at: string;
            owner_group: string;
            source_id: string;
            host: string;
            vendor: string;
            product: string;
            parser_id: string;
            parser_version: string;
            parse_status: string;
            /** Format: uint32 */
            parse_generation: number | string;
            encoding_detected: string;
            template_id: string;
            /** Format: uint8 */
            severity_num: number | string;
            /** Format: uint32 */
            ocsf_class_uid: number | string;
            /** Format: uint16 */
            ocsf_activity_id: number | string;
            src_ip: string;
            dst_ip: string;
            /** Format: uint16 */
            src_port: number | string;
            /** Format: uint16 */
            dst_port: number | string;
            proto: string;
            action: string;
            outcome: string;
            user_name: string;
            attrs: {
                [key: string]: string;
            };
            body: string;
            raw_ref: string;
        };
        EventSearchRequest: {
            /** Format: date-time */
            from?: null | string;
            /** Format: date-time */
            to?: null | string;
            full_text?: null | string;
            filters?: components["schemas"]["FieldFilterRequest"][];
            owner_groups?: string[];
            source_ids?: string[];
            parse_statuses?: string[];
            /** Format: date-time */
            after_timestamp?: null | string;
            /** Format: uuid */
            after_event_id?: null | string;
            /** Format: int32 */
            limit?: number | string;
            ascending?: boolean;
        };
        EventSearchResponse: {
            events: components["schemas"]["EventResponse"][];
            next: null | components["schemas"]["EventCursorResponse"];
            has_more: boolean;
        };
        FieldFilterRequest: {
            field: string;
            op: string;
            values: string[];
        };
        FieldFilterResponse: {
            field: string;
            op: string;
            values: string[];
        };
        JsonElement: unknown;
        MaintenanceWindowListResponse: {
            windows: components["schemas"]["MaintenanceWindowResponse"][];
        };
        MaintenanceWindowRequest: {
            ownerGroup: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: uuid */
            ruleId: null | string;
            reason: string;
        };
        MaintenanceWindowResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            rule_id: null | string;
            owner_group: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            reason: string;
            created_by: string;
        };
        NotificationChannelListResponse: {
            /** Format: int32 */
            count: number | string;
            channels: components["schemas"]["NotificationChannelResponse"][];
        };
        NotificationChannelRequest: {
            name: string;
            channelType: string;
            ownerGroup: string;
            secret?: null | string;
            enabled?: boolean;
            headers?: {
                [key: string]: string;
            };
            host?: string;
            /** Format: int32 */
            port?: number | string;
            from?: string;
            to?: string[];
            user?: string;
            useStartTls?: boolean;
        };
        NotificationChannelResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            channel_type: string;
            owner_group: string;
            enabled: boolean;
            secret_set: boolean;
            settings: components["schemas"]["ChannelSettingsResponse"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ParserAuthoringResponse: {
            /** Format: uuid */
            id: null | string;
            parser_id: null | string;
            version: null | string;
            state: null | string;
            error: string;
            verdict: null | components["schemas"]["PublishVerdictResponse"];
        };
        ParserCoverageEntryResponse: {
            parser_id: string;
            /** Format: int32 */
            wins: number | string;
        };
        ParserDetailResponse: {
            summary: components["schemas"]["ParserSummaryResponse"];
            match: components["schemas"]["ParserMatchResponse"];
            /** Format: int32 */
            steps: number | string;
            groks: components["schemas"]["ParserGrokResponse"];
        };
        ParserDraftDetailResponse: {
            /** Format: uuid */
            id: string;
            parser_id: string;
            version: string;
            state: string;
            owner: string;
            yaml: string;
            verdict: components["schemas"]["PublishVerdictResponse"];
            /** Format: date-time */
            updated_at: string;
            previous_version: null | string;
            previous_yaml: null | string;
        };
        ParserDraftListResponse: {
            /** Format: int32 */
            count: number | string;
            drafts: components["schemas"]["ParserDraftResponse"][];
        };
        ParserDraftRequest: {
            yaml: string;
        };
        ParserDraftResponse: {
            /** Format: uuid */
            id: string;
            parser_id: string;
            version: string;
            vendor: string;
            product: string;
            state: string;
            owner: string;
            /** Format: int32 */
            passing_tests: number | string;
            quarantined: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            published_at: null | string;
        };
        ParserGrokResponse: {
            /** Format: int32 */
            total: number | string;
            /** Format: int32 */
            backtracking: number | string;
            fallback_reasons: string[];
        };
        ParserListResponse: {
            /** Format: int32 */
            count: number | string;
            parsers: components["schemas"]["ParserSummaryResponse"][];
            /** Format: int32 */
            backtracking_groks: number | string;
        };
        ParserMatchResponse: {
            transport: string[];
            contains: string[];
            source_labels: {
                [key: string]: string;
            };
        };
        ParserPublishResponse: {
            draft: components["schemas"]["ParserAuthoringResponse"];
            catalog: components["schemas"]["CatalogReloadResponse"];
        };
        ParserSummaryResponse: {
            id: string;
            version: string;
            vendor: string;
            product: string;
            description: string;
            license: string;
            /** Format: int32 */
            specificity: number | string;
            /** Format: int32 */
            backtracking_groks: number | string;
        };
        ParserTryRequest: {
            line: string;
            /** @default  */
            parserId: string;
        };
        PreviewPointResponse: {
            /** Format: date-time */
            at: string;
            /** Format: int64 */
            count: number | string;
            /** Format: double */
            value: number | string;
        };
        PreviewSourceResponse: {
            source_id: string;
            owner_group: string;
            /** Format: date-time */
            last_seen: null | string;
            gaps_seconds: (number | string)[];
        };
        PublishVerdictResponse: {
            ok: boolean;
            /** Format: int32 */
            passing_tests: number | string;
            errors: string[];
            warnings: string[];
        };
        ReplayRequest: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            parserId?: string;
            parserVersion?: string;
            ownerGroups?: string[];
            sourceIds?: string[];
            dryRun?: boolean;
            continueOnMissingObjects?: boolean;
        };
        SourceListResponse: {
            /** Format: int32 */
            count: number | string;
            sources: components["schemas"]["SourceResponse"][];
        };
        SourceResponse: {
            source_id: string;
            owner_group: string;
            peer_address: null | string;
            hostname: null | string;
            vendor: string;
            product: string;
            parser_id: null | string;
            encoding: string;
            source_class: string;
            enabled: boolean;
            is_known_to_dispatcher: boolean;
        };
        SourceUpsertRequest: {
            sourceId: string;
            ownerGroup: string;
            peerAddress?: null | string;
            hostname?: null | string;
            vendor?: string;
            product?: string;
            parserId?: null | string;
            encoding?: string;
            sourceClass?: string;
            enabled?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OtlpLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-protobuf": string;
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReceiveChangeWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpointId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PipelineHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Replay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RollbackParser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parserId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParserPublishResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ParserCoverage: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogCoverageResponse"];
                };
            };
        };
    };
    SearchEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventSearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSearchResponse"];
                };
            };
        };
    };
    GetEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetEventRaw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRawResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceListResponse"];
                };
            };
        };
    };
    UpsertSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpsertRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportSourcesCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SearchChanges: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                targetId?: string;
                changeKind?: string;
                limit?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSearchResponse"];
                };
            };
        };
    };
    WriteChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeWriteRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeWriteResponse"];
                };
            };
        };
    };
    ListChangeConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorListResponse"];
                };
            };
        };
    };
    CreateChangeConnector: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectorRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorView"];
                };
            };
        };
    };
    GetChangeConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorView"];
                };
            };
        };
    };
    UpdateChangeConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectorRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorView"];
                };
            };
        };
    };
    DeleteChangeConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestChangeConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorTestResponse"];
                };
            };
        };
    };
    ListChangeConnectorRuns: {
        parameters: {
            query?: {
                limit?: number | string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorRunListResponse"];
                };
            };
        };
    };
    ListParsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParserListResponse"];
                };
            };
        };
    };
    GetParser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParserDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TryParser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParserTryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListParserDrafts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParserDraftListResponse"];
                };
            };
        };
    };
    CreateParserDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParserDraftRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetParserDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParserDraftDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateParserDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParserDraftRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubmitParserDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReturnParserDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParserAuthoringResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    PublishParserDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParserPublishResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParserAuthoringResponse"];
                };
            };
        };
    };
    ListAlertRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleListResponse"];
                };
            };
        };
    };
    CreateAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeleteAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PreviewAlertRule: {
        parameters: {
            query?: {
                lookbackSeconds?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPreviewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ListAlertTriggers: {
        parameters: {
            query?: {
                ruleId?: string;
                limit?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertTriggerListResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListMaintenanceWindows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceWindowListResponse"];
                };
            };
        };
    };
    CreateMaintenanceWindow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceWindowRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedIdResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeleteMaintenanceWindow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlertingStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertingStatsResponse"];
                };
            };
        };
    };
    ListNotificationChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannelListResponse"];
                };
            };
        };
    };
    CreateNotificationChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationChannelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannelResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    UpdateNotificationChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationChannelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannelResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeleteNotificationChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestNotificationChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelTestResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelTestResponse"];
                };
            };
        };
    };
}
